package com.schotanus.nobel;


import static com.schotanus.nobel.Tables.NOBEL_PRIZE;
import static com.schotanus.nobel.Tables.NOBEL_PRIZE_CATEGORY;
import static com.schotanus.nobel.Tables.NOBEL_PRIZE_LAUREATE;
import static com.schotanus.nobel.tables.Organization.ORGANIZATION;
import static com.schotanus.nobel.tables.Person.PERSON;

import jakarta.enterprise.context.ApplicationScoped;
import org.jooq.DSLContext;


/**
 * Data helper class to clean up test data.
 */
@ApplicationScoped
public class DataHelper {
    private final DSLContext dsl;

    public DataHelper(DSLContext dsl) {
        this.dsl = dsl;
    }

    public void deletePersonsWithTestIdentifiers() {
        dsl.delete(Tables.PERSON).where(PERSON.PERSONIDENTIFIER.like("test%")).execute();
    }

    public void deleteOrganizationsWithTestIdentifiers() {
        dsl.delete(Tables.ORGANIZATION).where(ORGANIZATION.ORGANIZATIONIDENTIFIER.like("test%")).execute();
    }

    /**
     * Deletes data generated by integration tests, that used category "Economics", before 1969,
     * since no Nobel Prizes for economics were awarded before 1969.
     */
    public void deleteNobelPrizeTestData() {
        dsl.delete(NOBEL_PRIZE_LAUREATE)
            .where(NOBEL_PRIZE_LAUREATE.NOBELPRIZEID.in(
                dsl.select(NOBEL_PRIZE.ID)
                    .from(NOBEL_PRIZE)
                    .join(NOBEL_PRIZE_LAUREATE).on(NOBEL_PRIZE_LAUREATE.NOBELPRIZEID.eq(NOBEL_PRIZE.ID))
                    .join(NOBEL_PRIZE_CATEGORY).on(NOBEL_PRIZE_CATEGORY.ID.eq(NOBEL_PRIZE.CATEGORYID))
                    .where(NOBEL_PRIZE_CATEGORY.CODE.eq("E"))
                        .and(NOBEL_PRIZE.YEAR.lt(1969))))
            .execute();

        dsl.delete(NOBEL_PRIZE).where(NOBEL_PRIZE.YEAR.lt(1969)).and(NOBEL_PRIZE.CATEGORYID.eq(6)).execute();

        deleteOrganizationsWithTestIdentifiers();
        deletePersonsWithTestIdentifiers();
    }
}
